export const PLAYER_CHOICE = 'PLAYER_CHOICE';
export const MACHINE_CHOICE = 'MACHINE_CHOICE';
export const GAME_RESULT = 'GAME_RESULT';
export const PLAY_AGAIN = 'PLAY_AGAIN';
export const GET_PREVIOUS_SCORE = 'GET_PREVIOUS_SCORE';
